/**
 * IMPORTANT:
 * THIS FILE IS AUTO-GENERATED
 * DO NOT EDIT THIS FILE BY HAND
*/
#ifndef OPUS_TEXTURE_GENERATED_H
#define OPUS_TEXTURE_GENERATED_H

#include <core/defines.h>
#include <core/math.h>
#include <gfx/sprite.h>
#include <engine/text.h>

typedef enum
{
	ANIMATION_UNDEFINED = 0,
	ANIMATION_ROBOTS_BASE_ROBOT,
	ANIMATION_COUNT
} ANIMATION_INDEX;

typedef enum
{
	SPRITE_UNDEFINED = 0,
	SPRITE_ROBOTS_BASE_ROBOT_0,
	SPRITE_ROBOTS_BASE_ROBOT_1,
	SPRITE_ROBOTS_BASE_ROBOT_2,
	SPRITE_ROBOTS_BASE_ROBOT_3,
	SPRITE_ROBOTS_BASE_ROBOT_4,
	SPRITE_COUNT
} SPRITE_INDEX;

typedef enum 
{
	TEXTURE_ROBOTS,
	TEXTURE_COUNT
} TEXTURE_INDEX;

internal const TEXTURE_INDEX texture_index_map[7] =
{
	TEXTURE_ROBOTS,
	TEXTURE_ROBOTS,
	TEXTURE_ROBOTS,
	TEXTURE_ROBOTS,
	TEXTURE_ROBOTS,
	TEXTURE_ROBOTS,
};

internal const Animation Animations[3] =
{
	{0},
	{ SPRITE_ROBOTS_BASE_ROBOT_0, SPRITE_ROBOTS_BASE_ROBOT_4 + 1 },
};

internal const Sprite Sprites[7] =
{
	{0},
	{ {    1,    1,  22,  22}, {   0,   0 }, {    0,    0,  22,  22}, {   22,   22 }},
	{ {   25,    1,  20,   9}, {   0,   0 }, {    0,    0,  20,   9}, {   22,   22 }},
	{ {   25,   12,   9,   9}, {   0,   0 }, {    0,    0,   9,   9}, {   22,   22 }},
	{ {   36,   12,   6,  12}, {   0,   0 }, {    0,    0,   6,  12}, {   22,   22 }},
	{ {   47,    1,  20,   6}, {   0,   0 }, {    0,    0,  20,   6}, {   22,   22 }},
};

internal const char* SpriteNames[7] =
{
	"NULL",
	"BASE_ROBOT_0",
	"BASE_ROBOT_1",
	"BASE_ROBOT_2",
	"BASE_ROBOT_3",
	"BASE_ROBOT_4",
};

#endif